import RootProviders from "@/components/providers";
import type { Metadata } from "next";
import "./global.css";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProviders>
          <Sidebar />
          {children}
        </RootProviders>
      </body>
    </html>
  );
}
